# cc -Wall -Werror -Wextra ft_display_file.c -o ft_display_file
ft_display_file: ft_display_file.c
	cc -Wall -Werror -Wextra $< -o $@

all: ft_display_file

clean:
	rm -f ft_display_file

fclean: clean